local LinearLayoutCompat = bindClass "androidx.appcompat.widget.LinearLayoutCompat"
local AppCompatImageView = bindClass "androidx.appcompat.widget.AppCompatImageView"
local MaterialCardView = bindClass "com.google.android.material.card.MaterialCardView"
local MaterialTextView = bindClass "com.google.android.material.textview.MaterialTextView"
local MaterialButton = bindClass "com.google.android.material.button.MaterialButton"

return {
  LinearLayoutCompat;
  orientation="vertical";
  layout_height="fill";
  layout_width="fill";
  id="base_layout",
  {
    LinearLayoutCompat;
    layout_margin="24dp",
    layout_width="match_parent";
    gravity="left|center";
    orientation="horizontal",
    id="top_bar",
    {
      MaterialCardView;
      CardElevation="0dp";
      radius="12dp";
      layout_width="24dp";
      layout_height="24dp";
      StrokeWidth="0dp",
      cardBackgroundColor=LuaThemeUtil.getColorPrimary(),
      visibility=8,
      id="icon_layout",
      {
        AppCompatImageView;
        layout_margin="3dp";
        layout_width="fill";
        layout_height="fill";
        id="icon",
        ColorFilter=LuaThemeUtil.getColorOnPrimary();
      };
    };
    {
      MaterialTextView;
      layout_marginLeft="15dp";
      id="title";
      layout_weight=1;
      gravity="left|center";
      textSize="16sp";
      layout_height="match_parent";
      textColor=LuaThemeUtil.getColorOnBackground(),
      ellipsize="end";
      MaxLines=1;
      textSize="16sp";
    };
    {
      AppCompatImageView;
      padding="3dp";
      layout_width="32dp";
      layout_height="32dp";
      id="close",
      ColorFilter=LuaThemeUtil.getColorOutline(),
      src=activity.getLuaDir().."/mods/dialog/bottomsheetdialog/close.png",
    };
  };
  {
    MaterialTextView,
    id="message",
    layout_marginLeft="24dp",
    layout_marginRight="24dp",
    layout_marginBottom="24dp",
    textColor=LuaThemeUtil.getColorOnSurfaceVariant(),
    visibility=8,
  },
  {
    LinearLayoutCompat,
    layout_width="match",
    layout_height="wrap",
    id="content",
    orientation="vertical",
    layout_marginLeft="24dp",
    layout_marginRight="24dp",
    layout_marginBottom="24dp",
    visibility=8,
  },
  {
    LinearLayoutCompat,
    layout_width="match",
    layout_height="50dp",
    id="button_layout",
    orientation="horizontal",
    layout_marginLeft="24dp",
    layout_marginRight="24dp",
    layout_marginBottom="24dp",
    visibility=8,
    {
      MaterialButton,
      layout_width="match",
      layout_weight=1,
      layout_height="match",
      id="negative_button",
      visibility=8,
      --style=MDC_R.attr.buttonBarButtonStyle,
      style=MDC_R.attr.materialButtonOutlinedStyle,
      layout_marginRight="24dp",
    },
    {
      MaterialButton,
      layout_width="match",
      layout_height="match",
      id="positive_button",
      visibility=8,
      layout_weight=1,
    },
  },
}